#pragma once


//Constants 
#define MAX_VALID_DISTANCE 3000

//First lap

#define FIRST_GO_STRAIGHT_DISTANCE 70
#define FIRST_GO_STRAIGHT_SPEED 50
#define FIRST_GO_STRAIGHT_ACCEL_DECCEL 30

#define EDGING_PWM -70
#define EDGING_TARGET_DISTANCE 300

#define INITIAL_REVERSE_TIME 1000
#define INITIAL_REVERSE_PWM 50
